#!/bin/sh

# SPDX-PackageSummary: finnix-live-build
# SPDX-FileComment: Finnix getting-started
# SPDX-FileCopyrightText: Copyright (C) 2021-2022 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

exec man getting-started
