#!/bin/sh

# SPDX-PackageSummary: finnix-live-build
# SPDX-FileComment: Finnix getting-started
# SPDX-FileCopyrightText: Copyright (C) 2021 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

PRODUCT_ID="{{ PRODUCT_ID }}"

exec pager "/usr/share/doc/${PRODUCT_ID}/getting-started.txt"
