#!/bin/sh

# SPDX-PackageName: finnix-live-build
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/finnix-live-build
# SPDX-FileCopyrightText: © 2024 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

set -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
prereqs)
    prereqs
    exit 0
    ;;
esac

PRODUCT_ID="{{ PRODUCT_ID }}"
INIT="/usr/lib/${PRODUCT_ID}/strace-init"
STRACE_INIT="0"

# shellcheck disable=SC2013
for arg in $(cat /proc/cmdline); do
    case "$arg" in
    init=*)
        # Allow overriding init=, even when running init.strace=1
        INIT="${arg#init=}"
        ;;
    init.strace=*)
        STRACE_INIT="${arg#init.strace=}"
        ;;
    esac
done

if [ "${STRACE_INIT}" = "1" ]; then
    echo "init=\"${INIT}\"" >>/conf/param.conf
fi
