#!/bin/sh

# SPDX-PackageSummary: finnix-live-build
# SPDX-FileComment: initramfs-machine-id
# SPDX-FileCopyrightText: Copyright (C) 2021-2022 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

set -e

PREREQS=""
rootmnt="${rootmnt:-}"  # Set by initrd environment

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

is_usable_product_uuid() {
    [ -e /sys/class/dmi/id/sys_vendor ] || return 1
    [ -e /sys/class/dmi/id/product_uuid ] || return 1
    [ "$(cat /sys/class/dmi/id/sys_vendor)" = "QEMU" ] && return 0
    return 1
}

MACHINE_ID=""
if is_usable_product_uuid; then
    # We can trust these vendors' product_uuid to be decent.
    MACHINE_ID="$(sed -e 's/-//g' /sys/class/dmi/id/product_uuid)"
elif [ -e /proc/device-tree/vm,uuid ]; then
    # DT vm,uuid will be unique, but can have a trailing null byte
    MACHINE_ID="$(sed -e 's/[-\x0]//g' /proc/device-tree/vm,uuid)"
elif [ -e /sys/firmware/dmi/tables/DMI ]; then
    # product_uuid is available, but isn't guaranteed to be decent on
    # all systems, so let's just hash the entire DMI.
    # Note that this isn't wise on a permanent machine, as it's
    # possible two exact machines (with broken vendor UUIDs/serials)
    # could have the exact same DMI, but it's fine in a live
    # environment.
    MACHINE_ID="$(md5sum /sys/firmware/dmi/tables/DMI | cut -d' ' -f1)"
elif [ -e /proc/sys/kernel/random/boot_id ]; then
    # Kernel boot ID (random per-boot)
    MACHINE_ID="$(sed -e 's/-//g' /proc/sys/kernel/random/boot_id)"
elif [ -e /proc/sys/kernel/random/uuid ]; then
    # Random ID
    MACHINE_ID="$(sed -e 's/-//g' /proc/sys/kernel/random/uuid)"
fi

rm -f "${rootmnt}/etc/machine-id" "${rootmnt}/var/lib/dbus/machine-id"
echo "${MACHINE_ID}" >"${rootmnt}/etc/machine-id"
mkdir -p "${rootmnt}/var/lib/dbus"
ln -s /etc/machine-id "${rootmnt}/var/lib/dbus/machine-id"
