#!/bin/sh

# SPDX-PackageName: finnix-live-build
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/finnix-live-build
# SPDX-FileComment: locale-config / 0 - Keyboard/locale reconfiguration
# SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

# Reconfigure keyboard/locale access in a fairly universal way,
# requiring the following keys on a potentially misconfigured keyboard:
# - 0
# - Enter
# - Arrow keys

set -e

dpkg-reconfigure keyboard-configuration
setupcon -k
# udevadm will not work in a container
udevadm trigger --subsystem-match=input --action=change || true
dpkg-reconfigure locales
echo
echo "Be sure to exit active shells to use new locale settings."
