#!/bin/sh

# SPDX-PackageSummary: finnix-live-build
# SPDX-FileComment: locale-config / 0 - Keyboard/locale reconfiguration
# SPDX-FileCopyrightText: Copyright (C) 2020-2022 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

# Reconfigure keyboard/locale access in a fairly universal way,
# requiring the following keys on a potentially misconfigured keyboard:
# - 0
# - Enter
# - Arrow keys

set -e

dpkg-reconfigure keyboard-configuration
setupcon -k
udevadm trigger --subsystem-match=input --action=change
dpkg-reconfigure locales
