#!/bin/sh

# SPDX-PackageName: finnix-live-build
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/finnix-live-build
# SPDX-FileComment: shared-ssh-agent
# SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

# systemd service

PRODUCT_ID="{{ PRODUCT_ID }}"

[ -n "${USER}" ] || exit 1
HOME="$(getent passwd "${USER}" | cut -d: -f6)"
export HOME

# shellcheck source=/dev/null
. "/usr/lib/${PRODUCT_ID}/ssh-agent"
systemd-notify --ready --pid="${SSH_AGENT_PID?}"
