#!/bin/sh

# SPDX-PackageSummary: finnix-live-build
# SPDX-FileComment: ssh-agent
# SPDX-FileCopyrightText: Copyright (C) 2020-2022 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

# Meant to be run from .profile or equivalent, to provide a per-user
# shared SSH agent environment

[ -n "${HOME}" ] || exit 1

if [ ! -e "${HOME}/.ssh/ssh-agent.sh" ]; then
    mkdir -p "${HOME}/.ssh"
    ssh-agent -s | grep ^SSH >"${HOME}/.ssh/ssh-agent.sh"
    # shellcheck source=/dev/null
    . "${HOME}/.ssh/ssh-agent.sh"
    echo "${SSH_AGENT_PID}" >"${HOME}/.ssh/ssh-agent.pid"
fi
# shellcheck source=/dev/null
. "${HOME}/.ssh/ssh-agent.sh"
