#!/bin/sh

# SPDX-PackageSummary: finnix-live-build
# SPDX-FileComment: sshd-keygen
# SPDX-FileCopyrightText: Copyright (C) 2020-2022 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

# Populates SSH host keys; called before starting sshd.

set -e

for fn in /etc/ssh/sshd_config /etc/ssh/sshd_config.d/*.conf; do
    [ -e "${fn}" ] || continue
    keytypes="$(sed -E 's,^#?HostKey .*/ssh_host_(.*?)_key,\1,;t;d' "${fn}")"
    for keytype in ${keytypes}; do
        if [ ! -e "/etc/ssh/ssh_host_${keytype}_key" ]; then
            ssh-keygen -q -f "/etc/ssh/ssh_host_${keytype}_key" -N "" -t "${keytype}"
        fi
    done
done
