#!/bin/sh

# SPDX-PackageSummary: finnix-live-build
# SPDX-FileComment: sshd-keygen
# SPDX-FileCopyrightText: Copyright (C) 2020-2022 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

# Populates SSH host keys; called before starting sshd.

set -e

for keytype in $(perl -ne 'm,^\#?HostKey .*/ssh_host_(.*?)_key, && print "$1\n"' /etc/ssh/sshd_config); do
    if [ ! -e "/etc/ssh/ssh_host_${keytype}_key" ]; then
        ssh-keygen -q -f "/etc/ssh/ssh_host_${keytype}_key" -N "" -t "${keytype}"
    fi
done
