#!/bin/sh

# sshd-keygen
# Copyright (C) 2020-2021 Ryan Finnie
# SPDX-License-Identifier: GPL-2.0+

# Populates SSH host keys; called before starting sshd.
# Ideally this should programatically figure out which host keys are
# configured in sshd_config, but for now it's a static list.

set -e

for keytype in ecdsa ed25519 rsa; do
    if [ ! -e "/etc/ssh/ssh_host_${keytype}_key" ] && grep -qs "ssh_host_${keytype}_key" /etc/ssh/sshd_config; then
        ssh-keygen -q -f "/etc/ssh/ssh_host_${keytype}_key" -N "" -t "${keytype}"
    fi
done
