#!/bin/sh

# SPDX-PackageSummary: finnix-live-build
# SPDX-FileComment: strace-init
# SPDX-FileCopyrightText: Copyright (C) 2012-2022 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

# Called as:
#     init=/usr/lib/{{ PRODUCT_ID }}/strace-init
# Once booted, wait about 10 seconds before running `killall strace`.
# Use the `tools/strace-reorder` program in finnix-live-build to
# convert to a sort format usable by mksquashfs:
#     tools/strace-reorder <strace-init.trace >squashfs.sort

set -e

PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

strace -v -qq -yy -s 65535 -p $$ -f -e open,openat,execve -z -o /var/log/strace-init.trace &
sleep 3
if [ -n "$1" ]; then
  exec "$@"
else
  exec /sbin/init
fi
