#!/bin/sh

# SPDX-PackageName: finnix-live-build
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/finnix-live-build
# SPDX-FileComment: strace-init
# SPDX-FileCopyrightText: © 2012 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

# Called as: init.strace=1
# Once booted, wait about 10 seconds before running `killall strace`.
# Use the `tools/strace-reorder` program in finnix-live-build to
# convert to a sort format usable by mksquashfs:
#     tools/strace-reorder </var/log/strace-init.trace >squashfs.sort

set -e

PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"

exec strace \
    --daemonize=session \
    --no-abbrev \
    --quiet=all \
    --decode-fds=all \
    --string-limit=65535 \
    --follow-forks \
    --successful-only \
    --interruptible=anywhere \
    --output=/var/log/strace-init.trace \
    --trace=open,openat,execve \
    /sbin/init "$@"
