#!/bin/bash

# SPDX-PackageName: finnix-live-build
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://forge.colobox.com/finnix/finnix-live-build
# SPDX-FileCopyrightText: © 2024 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

set -e

cmd="$1"
shift
if [ -z "${cmd}" ]; then
    cmd=bash
fi
# /tmp/_defaultcwd is the Dockerfile default; unless overridden, use the user's home directory
if [ "$(pwd)" = "/tmp/_defaultcwd" ]; then
    cd
fi
mapfile -t env < <(
    grep -h '^[A-Z]' /etc/environment /etc/locale.conf
    env
)
exec env -- "${env[@]}" "${cmd}" "$@"
