#!/bin/sh

set -e
set -x

if [ -e /etc/dnf/dnf.conf ]; then
    # (SC2046) Word splitting is desired here
    # shellcheck disable=SC2046
    sudo dnf -y install $(tools/get-dependencies build-dependencies.json)
else
    sudo apt update
    # (SC2046) Word splitting is desired here
    # shellcheck disable=SC2046
    sudo apt -y install $(tools/get-dependencies build-dependencies.json)
fi

# Build image
sudo chown -R root:root .
sudo env ARCH="${ARCH}" BUILD_TAGS="rrpcid ci ${BUILD_TAGS}" ./finnix-live-build
sudo rm -rf build/cache/lb/bootstrap build/cache/lb/contents.chroot build/cache/lb/indices.bootstrap
sudo chown -R "$(id -un):$(id -gn)" .

# Save artifacts
mkdir -p .rrpcid/artifacts
mv \
    build/lb/finnix-* \
    build/lb/chroot.files \
    build/lb/chroot.packages.* \
    .rrpcid/artifacts/
