#!/bin/sh

set -e
set -x

# Dependency packages
sudo apt update
# (SC2046) Word splitting is desired here
# shellcheck disable=SC2046
sudo apt -y install $(cat build-dependencies.txt)

# Lint codebase
env LINT=true ARCH="${ARCH}" BUILD_TAGS="rrpcid ci ${BUILD_TAGS}" ./finnix-live-build

# Build image
sudo env ARCH="${ARCH}" BUILD_TAGS="rrpcid ci ${BUILD_TAGS}" ./finnix-live-build

# Save artifacts
mkdir -p .rrpcid/artifacts
sudo mv \
    build/lb/finnix-* \
    build/lb/chroot.files \
    build/lb/chroot.packages.* \
    .rrpcid/artifacts/
sudo chown -R "$(id -un):$(id -gn)" .rrpcid/artifacts
