#!/usr/bin/env python3

# finnix-strace-reorder
# Copyright (C) 2011-2020 Ryan Finnie
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os
import re
import sys


SQUASHFS_ROOT = "/run/live/rootfs/filesystem.squashfs"

R_OPEN = re.compile(r"^[0-9]+ +(open|openat)\(.*?\) = [0-9]+<(.*?)>$")
R_EXEC = re.compile(r"^[0-9]+ +(execve)\(\"(.*?)\".*?\) = [0-9]+$")


def get_filename(line):
    m = re.search(R_OPEN, line)
    if m:
        return m.group(2)
    m = re.search(R_EXEC, line)
    if m:
        return m.group(2)


if __name__ == "__main__":
    seen = []
    for line in sys.stdin.readlines():
        filename = get_filename(line.rstrip())
        if not filename:
            continue
        if not os.path.isfile(os.path.join(SQUASHFS_ROOT, filename[1:])):
            continue
        if filename in seen:
            continue
        seen.append(filename)

    pos = -1
    for filename in seen:
        print("{}\t{}".format(filename[1:], pos))
        pos -= 1
