#!/usr/bin/env python3

# jinja2-render
# Copyright (C) 2020-2021 Ryan Finnie
# SPDX-License-Identifier: MPL-2.0

import os
import sys

from jinja2 import Template


if __name__ == "__main__":
    tmpl = Template(sys.stdin.read())
    vars = dict(os.environ)
    print(tmpl.render(vars))
