#!/usr/bin/env python3

# SPDX-PackageName: finnix-live-build
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/finnix-live-build
# SPDX-FileComment: jinja2-render
# SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

import os
import sys

from jinja2 import Template


if __name__ == "__main__":
    tmpl = Template(sys.stdin.read())
    vars = dict(os.environ)
    print(tmpl.render(vars))
