# SPDX-PackageName: finnix-live-build
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://codeberg.org/finnix/finnix-live-build
# SPDX-FileComment: Woodpecker CI ci workflow
# SPDX-FileCopyrightText: © 2026 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0
---
when:
  - event: ["push", "pull_request", "manual", "cron"]
    cron: "weekly"
matrix:
  include:
    - ARCH: "amd64"
      PLATFORM: "linux/amd64"
    - ARCH: "arm64"
      PLATFORM: "linux/arm64"
labels:
  platform: "${PLATFORM}"
clone:
  git:
    image: "woodpeckerci/plugin-git"
    settings:
      # finnix-live-build can use tags to make more descriptive dev IDs
      tags: true
steps:
  - name: "CI build (${ARCH})"
    image: "finnix/finnix:latest"
    commands: |
      set -x
      apt update
      apt -y install git python3 curl
      tools/get-dependencies --only required -0 | xargs -0 apt -y install
      tools/get-dependencies --only optional | while IFS='' read -r pkg; do
        apt -y install "$${pkg}" || true
      done
      ./finnix-live-build
      rm -rf build/cache/lb/bootstrap build/cache/lb/contents.chroot build/cache/lb/indices.bootstrap

      # Source ISO
      if [ "$${CI_SOURCE_ISO}" = "true" ]; then
        temp_build_dir="$(mktemp -d -p "$(pwd)/build")"
        env SOURCE_ISO=true BUILD_DIR="$${temp_build_dir?}" ./finnix-live-build
        mv "$${temp_build_dir}/lb/finnix-source.iso" build/lb/
        rm -rf "$${temp_build_dir?}"
        echo "Note: The build information listed above is not used; only the source ISO is saved."
        echo "See previous for actual build information."
      fi

      artifact_fn="${CI_REPO_NAME}-${CI_PIPELINE_CREATED}-${CI_WORKFLOW_NAME}-$${ARCH}-${CI_PIPELINE_NUMBER}.tar.gz"
      mkdir -p .artifacts-dist
      tar zcvf ".artifacts-dist/$${artifact_fn}" \
        build/lb/finnix-* \
        build/lb/chroot.files \
        build/lb/chroot.packages.*
      curl --fail-with-body -T ".artifacts-dist/$${artifact_fn}" -H "Authorization: Basic $${ASSETS_AUTH}" "http://artifacts.snowman.lan/$${artifact_fn}"
      {
          echo "### Artifacts"
          echo ""
          echo "- http://artifacts.snowman.lan/$${artifact_fn}"
          echo ""
      } >>"$${CI_WORKSPACE}/.ci-pipeline-summary"
    environment:
      ASSETS_AUTH:
        from_secret: "ASSETS_AUTH"
  - name: "Notify Mastodon if failure"
    when:
      - status: ["failure"]
    image: "woodpeckerci/plugin-mastodon-post"
    settings:
      server_url: "https://m29.us"
      access_token:
        from_secret: "m29_token"
      status: |
        🪿 🪿 🪿 FAILURE: {{ CI_REPO }} 🪿 🪿 🪿
        Workflow: {{ CI_WORKFLOW_NAME }} ({{ CI_PIPELINE_EVENT }} on {{ CI_COMMIT_REF }})

        Pipeline: {{ CI_PIPELINE_URL }}
        Commit: {{ CI_PIPELINE_FORGE_URL }}
  - name: "Pipeline summary"
    image: "finnix/finnix:latest"
    commands: |
      if [ -e "$${CI_WORKSPACE}/.ci-pipeline-summary" ]; then cat "$${CI_WORKSPACE}/.ci-pipeline-summary"; fi
